[package]
name = "anastasia-provider-antigravity"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
anastasia-provider-gemini = { path = "../anastasia-provider-gemini" }
anastasia-schema-dialect = { path = "../anastasia-schema-dialect" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
